services:
  database:
    image: ghcr.io/railwayapp-templates/postgres-ssl:16
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - .env.fixed
      - .env.user

  trading-bot:
    image: aureumvictoria/uncoded-trading-bot:2025.09.09
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env.fixed
      - .env.user

  telegram-bot:
    image: aureumvictoria/uncoded-telegram-bot:2025.09.21
    restart: unless-stopped
    depends_on:
      - trading-bot
    env_file:
      - .env.fixed
      - .env.user

volumes:
  database-data:
